name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          # Ustawienie prawidłowej ścieżki bazowej (jak ustaliliśmy)
          base-url-path: https://emkamil.github.io/wielka-tercja
          
          # Wskazuje katalog, w którym znajdują się pliki HTML
          path-to-root: ./
          
          # Włącza skanowanie plików HTML
          include-html: true
          
          # NOWA ZMIANA: Wyklucza wszystkie pliki HTML w katalogu 'exercises' i jego podkatalogach
          # Wzór 'exercises/**' wyklucza pliki wewnątrz katalogu exercises
          # Wzór '404.html' wyklucza pojedynczy plik błędu
          exclude-paths: '404.html, exercises/**'
      - name: Commit and Push Sitemap # Zapisuje i wysyła plik sitemap.xml do repozytorium
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "SEO: Automatyczna aktualizacja sitemap.xml przez GitHub Action"
          file_pattern: sitemap.xml
